export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const SELECT_USER_PROFILE_REQUEST = "SELECT_USER_PROFILE_REQUEST"
export const SELECT_USER_PROFILE_SUCCESS = "SELECT_USER_PROFILE_SUCCESS"
export const SELECT_USER_PROFILE_FAILURE = "SELECT_USER_PROFILE_FAILURE"